Repository beyond-sw-camp/be12-fin-HOT6-Petlog-FE, pull requests merged in 2025-04, with the labels that each got.

#1 헤더 컴포넌트, 랜딩 페이지 구현
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/vite.svg
  src/App.vue
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/images/cat1.jpg
  src/assets/images/cat2.jpg
  src/assets/images/dog1.png
  src/assets/images/dog2.jpeg
  src/assets/images/logo.png
  src/assets/images/main_image.png
  src/assets/images/profile_1.jpg
  src/assets/vue.svg
  src/components/HelloWorld.vue
  src/components/common/Header.vue
  src/main.js
  src/pages/admin/.gitkeep
  src/pages/board/.gitkeep
  src/pages/chat/.gitkeep
  src/pages/home/Home.vue
  src/pages/home/LandingPage.vue
  src/pages/mypage/.gitkeep
  src/pages/place/.gitkeep
  src/pages/schedule/.gitkeep
  src/reset.css
  src/router/index.js
  src/style.css
Labels: Feat

#4 [Feat} 마이페이지 사이드바 구현
  src/pages/mypage/Mypage.vue
Labels: Feat

#6 헤더 로고 클릭 시 홈 이동, 기타 스타일 수정
  src/App.vue
  src/components/common/Header.vue
  src/pages/home/LandingPage.vue
  src/router/index.js
  src/style.css
Labels: Chore, Style

#11 [Feat] 사이드바 css 수정
  src/pages/mypage/Mypage.vue
Labels: Style

#18 [Feat] 마이페이지 CSS 수정
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageAnswer.vue
  src/pages/mypage/MypageCardList.vue
  src/pages/mypage/MypageComment.vue
  src/pages/mypage/MypagePost.vue
  src/pages/mypage/MypageProfile.vue
  src/pages/mypage/MypageQuestion.vue
Labels: Style

#23 [Feat
  src/pages/admin/AdminCategory.vue
  src/pages/admin/BoardCategory.vue
  src/pages/admin/BoardCategoryFix.vue
  src/pages/admin/Record.vue
  src/pages/admin/RecordFix.vue
  src/pages/admin/Schedule.vue
  src/pages/admin/ScheduleFix.vue
  src/pages/mypage/MypageCardList.vue
  src/router/index.js
Labels: Feat

#46 [Feat] 로그인 홈 화면 구현!
  src/assets/icons/calendar.png
  src/assets/icons/chat.png
  src/pages/home/Home.vue
  src/pages/home/ScheduleCard.vue
Labels: Feat

#49 [Chore] 파일/경로 이름 수정, 폴더 구조 변경
  src/App.vue
  src/assets/icons/alart.png
  src/pages/admin/ModifyScheduleCategory.vue
  src/pages/admin/ScheduleCategory.vue
  src/pages/common/Home.vue
  src/pages/common/LandingPage.vue
  src/pages/common/components/Header.vue
  src/pages/common/components/ScheduleCard.vue
  src/pages/user/UserLayout.vue
  src/router/index.js
Labels: Chore

#50 [Feat] 헤더 드롭다운 기능 개발
  src/pages/admin/.gitkeep
  src/pages/common/components/Header.vue
  src/pages/common/components/HeaderDropdown.vue
  src/pages/mypage/.gitkeep
Labels: Feat

#54 [Feat] 계정 삭제 기능 추가
  src/pages/mypage/MypageProfile.vue
  src/pages/mypage/components/MypageDelete.vue
Labels: Feat

#57 [Fix] router 수정, 스타일 수정
  src/pages/admin/Admin.vue
  src/pages/chat/ChatRoom.vue
  src/pages/common/LandingPage.vue
  src/pages/common/components/Header.vue
  src/pages/mypage/Mypage.vue
  src/router/index.js
  src/style.css
Labels: Fix, Style

#59 [Feat] 지도 전화번호 추가
  src/pages/place/KakaoMap.vue
  src/pages/place/SearchBeauty.vue
  src/pages/place/SearchHospital.vue
Labels: Fix

#60 Feature/place
  src/pages/common/components/Header.vue
  src/pages/common/components/NoticeDropdown.vue
  src/pages/place/KakaoMap.vue
  src/pages/place/SearchBeauty.vue
  src/pages/place/SearchHospital.vue
Labels: Fix

#61 [Fix] 페이지 명 수정
  .gitignore
  src/App.vue
  src/pages/admin/AdminPasswordModal.vue
  src/pages/admin/ModifyBoardCategory.vue
  src/pages/admin/ModifyRecordCategory.vue
  src/pages/admin/RecordCategory.vue
  src/pages/mypage/ModifyMypageCard.vue
  src/pages/mypage/MypagePasswordModal.vue
  src/pages/place/.gitkeep
Labels: Fix

#62 [Fix] 이름 수정
  src/pages/admin/AdminProfile.vue
  src/pages/mypage/MypageProfile.vue
  src/router/index.js
Labels: Fix

#67 [Fix] 마이페이지 css 수정
  src/pages/mypage/ModifyMypageCard.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageCardCreate.vue
  src/pages/mypage/MypageCardList.vue
  src/pages/mypage/MypageProfile.vue
Labels: Fix

#71 [Fix] 알림 드롭다운 css 수정
  src/App.vue
  src/pages/common/components/NoticeDropdown.vue
Labels: Fix

#76 [Fix] 카테고리 스토어 개발
  src/pages/admin/BoardCategory.vue
  src/pages/admin/RecordCategory.vue
  src/pages/admin/ScheduleCategory.vue
  src/pages/admin/components/CategoryItem.vue
  src/stores/useBoardCategoryStore.js
  src/stores/useRecordCategoryStore.js
  src/stores/useScheduleCategoryStore.js
Labels: Fix

#78 [Fix] 헤더 수정정
  src/pages/common/components/Header.vue
Labels: Fix

#79 [Feat] 새 기록 만들기, 일정 상세 페이지 구현
  src/pages/schedule/Schedule.vue
  src/pages/schedule/components/Calendar.vue
  src/pages/schedule/components/DetailSchedule.vue
  src/pages/schedule/components/NewScheduleModal.vue
  src/pages/schedule/components/ScheduleCard.vue
  src/stores/useScheduleStore.js
  src/style.css
  src/utils/color.js
  src/utils/dateFormat.js
Labels: Feat

#83 [Fix] 기록 카테고리 CSS 이슈 고침
  src/pages/admin/RecordCategory.vue
Labels: Fix

#84 [Fix] 스토어 수정
  src/stores/useBoardCategoryStore.js
  src/stores/useMypageCard.js
  src/stores/useRecordCategoryStore.js
  src/stores/useScheduleCategoryStore.js
Labels: Fix

#92 [Feat] 회원가입/로그인 기능 백엔드와 연동
  .gitignore
  package-lock.json
  package.json
  src/main.js
  src/pages/common/LandingPage.vue
  src/pages/common/components/Header.vue
  src/pages/user/Login.vue
  src/pages/user/Signup.vue
  src/stores/useUserStore.js
  vite.config.js
Labels: Feat

#96 [Fix] mypage 대수정
  src/pages/mypage/MypageCard.vue
  src/pages/mypage/MypageCardCreate.vue
  src/pages/mypage/MypageCardDetail.vue
  src/pages/mypage/MypageCardList.vue
  src/pages/mypage/MypageComment.vue
  src/pages/mypage/MypagePost.vue
  src/pages/mypage/MypageQuestion.vue
  src/router/index.js
  src/stores/useMypageCard.js
Labels: Fix

#97 [Feat] 카카오 로그인/회원가입 구현
  src/pages/user/Login.vue
  src/pages/user/Signup.vue
  src/stores/useUserStore.js
Labels: Feat

#99 [Fix] Card 중성화 표시 수정
  package-lock.json
  src/pages/mypage/MypageCardCreate.vue
  src/pages/mypage/MypageCardDetail.vue
Labels: Fix

#105 [Feat] 이메일 인증 구현
  src/pages/user/Login.vue
  src/stores/useUserStore.js
Labels: Feat

#108 [Fix] 반려동물 삭제 수정
  src/pages/mypage/ModifyMypageCard.vue
  src/pages/mypage/MypageCardDetail.vue
Labels: Fix

#109 [Fix] 로그인 여부에 따라 redirect, oauth2 토큰에 idx 추가
  src/main.js
  src/pages/common/HomePage.vue
  src/pages/common/LandingPage.vue
  src/pages/common/components/Header.vue
  src/pages/user/Login.vue
  src/pages/user/Signup.vue
  src/router/index.js
  src/stores/useUserStore.js
Labels: Fix

#112 [Fix] 로그인 시 홈페이지 변동
  src/pages/common/HomePage.vue
  src/pages/mypage/MypageCardDetail.vue
  src/router/index.js
  src/stores/useUserStore.js
Labels: Fix

#113 [Fix] router 수정
  src/pages/common/LandingPage.vue
  src/pages/user/Login.vue
Labels: bug

#114 [Fix] loading 추가
  src/App.vue
  src/pages/common/HomePage.vue
  src/pages/common/components/Header.vue
Labels: bug, Fix

#118 [Fix] api 요청 수정
  src/pages/mypage/ModifyMypageCard.vue
  src/pages/mypage/MypageCardCreate.vue
  src/pages/mypage/MypageCardDetail.vue
  src/pages/mypage/MypageCardList.vue
  src/pages/mypage/MypageProfile.vue
  src/stores/useMypageCard.js
Labels: Fix

#119 [Fix] aws S3 사진 업로드
  src/pages/mypage/MypageCardCreate.vue
Labels: Feat

#120 [Fix] 프로필 사진 기능
  src/pages/mypage/MypageProfile.vue
Labels: Fix

#121 [Fix] 사진 기능 & 게시판 유저별 조회
  src/pages/mypage/MypageCardList.vue
  src/pages/mypage/MypagePost.vue
Labels: Fix

#122 [Fix] 나의 질문 조회
  src/pages/board/components/QuestionCard.vue
  src/pages/mypage/MypageQuestion.vue
Labels: Fix

#123 [Fix] 마이페이지 답변 수정
  src/pages/board/components/AnswerCard.vue
  src/pages/mypage/MypageAnswer.vue
Labels: Fix

#126 [Fix] 댓글 조회 기능
  src/pages/board/components/CommentCard.vue
  src/pages/mypage/MypageComment.vue
Labels: Fix

#133 [Fix] usemypagestore 작성
  src/pages/mypage/ModifyMypageCard.vue
  src/pages/mypage/MypageCardCreate.vue
  src/pages/mypage/MypageCardDetail.vue
  src/pages/mypage/MypageCardList.vue
  src/pages/mypage/MypageComment.vue
  src/pages/mypage/MypagePost.vue
  src/pages/mypage/MypageProfile.vue
  src/pages/mypage/MypageQuestion.vue
  src/stores/useMypageCard.js
  src/stores/usePetStore.js
Labels: Fix

#134 [Fix] 카테고리 기능 강화
  src/pages/board/FreeBoard.vue
  src/pages/board/InformationBoard.vue
  src/pages/board/PostCreate.vue
Labels: Fix

#135 [Fix] 마이페이지 css 수정
  src/pages/mypage/MypageAnswer.vue
  src/pages/mypage/MypageComment.vue
  src/pages/mypage/MypagePost.vue
  src/pages/mypage/MypageQuestion.vue
Labels: Fix

#137 [Fix] 일정, 카테고리 기능 강화
  src/pages/common/components/SelectPetModal.vue
  src/pages/mypage/MypageCardList.vue
  src/pages/schedule/Schedule.vue
  src/pages/schedule/components/NewScheduleModal.vue
  src/stores/useCategoryStore.js
  src/stores/usePetStore.js
Labels: Fix

#138 [Fix] 유저 펫 연동
  src/pages/mypage/ModifyMypageCard.vue
  src/pages/mypage/MypageCardDetail.vue
  src/stores/usePetStore.js
Labels: Fix

#139 [Fix] 펫카드 수정 기능
  src/pages/mypage/ModifyMypageCard.vue
  src/stores/usePetStore.js
Labels: Fix

#140 [Feat] 기록 생성 기능, 날짜별 기록 조회 기능 구현
  src/pages/schedule/Schedule.vue
  src/pages/schedule/components/DetailList.vue
  src/pages/schedule/components/NewScheduleModal.vue
  src/pages/schedule/components/ScheduleCard.vue
  src/stores/useScheduleStore.js
  src/utils/dateFormat.js
Labels: Feat

#141 [Fix] Feature/mypage
  src/pages/admin/Admin.vue
  src/pages/mypage/MypageAnswer.vue
  src/pages/mypage/MypageQuestion.vue
Labels: Fix

#148 [Feat] 알림기능
  src/pages/common/components/NoticeDropdown.vue
  src/stores/useNoticeStore.js
Labels: Feat

#150 [Feat] 일정/기록 상세 조회 구현, 반려동물별 일정 조회 구현, 날짜별 일정/기록 전체 조회 구현
  src/pages/common/components/SelectPetModal.vue
  src/pages/mypage/MypageCardList.vue
  src/pages/schedule/DetailSchedule.vue
  src/pages/schedule/Schedule.vue
  src/pages/schedule/components/Calendar.vue
  src/pages/schedule/components/DetailItem.vue
  src/pages/schedule/components/DetailList.vue
  src/pages/schedule/components/DetailRecordItem.vue
  src/pages/schedule/components/NewScheduleModal.vue
  src/pages/schedule/components/ScheduleCard.vue
  src/stores/useMypageCard.js
  src/stores/usePetStore.js
  src/stores/useScheduleStore.js
  src/utils/dateFormat.js
Labels: Feat

#151 [Feat] 알림 기능
  src/pages/common/components/Header.vue
  src/pages/common/components/NoticeDropdown.vue
  src/stores/useMypageCard.js
  src/stores/useNoticeStore.js
Labels: Feat

#152 [Fix] url 수정
  src/stores/usePetStore.js
Labels: Fix

#156 [Fix] 비밀번호 변경 기능
  src/pages/mypage/MypagePasswordModal.vue
  src/pages/mypage/MypageProfile.vue
  src/stores/useMypageCard.js
Labels: Fix

#166 [Fix] 알림에 반려동물 이름 추가
  src/pages/common/components/NoticeDropdown.vue
  src/stores/useNoticeStore.js
Labels: Fix

#172 [Fix] 비밀번호 변경 & 카드 생성시 이미지 삽입
  src/assets/images/image_not_found.png
  src/pages/mypage/MypageCardCreate.vue
  src/pages/mypage/MypagePasswordModal.vue
Labels: Fix

#175 [Fix] 리드미 이미지 수정
  README.md
  src/assets/images/냐옹이.jpg
  src/assets/images/로사.jpg
  src/assets/images/로이.jpg
  src/assets/images/마자용.jpg
Labels: Fix

#177 [Feat] 로딩 상태 추가
  src/pages/common/components/LoadingSpinner.vue
  src/pages/user/Login.vue
  src/pages/user/Signup.vue
  src/stores/useLoadingStore.js
  src/stores/useUserStore.js
Labels: Feat

#180 [Feat] 유저 삭제 & 유저 복구
  src/pages/admin/AdminProfile.vue
  src/pages/common/components/Header.vue
  src/pages/mypage/MypageProfile.vue
  src/stores/useAdminStore.js
  src/stores/useProfileStore.js
  src/stores/useUserStore.js
Labels: Feat

#185 [Fix] 알림 클릭시 이동
  src/pages/common/components/NoticeDropdown.vue
  src/stores/useNoticeStore.js
Labels: Fix

#186 [Feat] 이메일 중복 확인 기능 구현, 회원 탈퇴 기능 구현
  src/assets/icons/delete_user.svg
  src/pages/mypage/MypageProfile.vue
  src/pages/user/DeletedUser.vue
  src/pages/user/Login.vue
  src/pages/user/Signup.vue
  src/router/index.js
  src/stores/useUserStore.js
Labels: Feat

#190 [Fix] 탈퇴 회원 조회
  src/pages/admin/AdminProfile.vue
  src/stores/useAdminStore.js
Labels: Fix
